//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDetail
    {
        public AttendanceDetail()
        {
            this.AttendanceMasters = new HashSet<AttendanceMaster>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public string TrainingOn { get; set; }
        public Nullable<int> Hour { get; set; }
        public Nullable<int> Mentor { get; set; }
        public Nullable<int> PersonId { get; set; }
    
        public virtual ICollection<AttendanceMaster> AttendanceMasters { get; set; }
        public virtual Person Person { get; set; }
    }
}
